const LEAGUES = [

  { name: "ligue-des-champions-uefa", url: "https://www.footmercato.net/classement/europe/ligue-des-champions-uefa?partial=1" },
  { name: "france-ligue-1", url: "https://www.footmercato.net/classement/france/ligue-1?partial=1" },
  { name: "spain-liga", url: "https://www.footmercato.net/classement/espagne/liga?partial=1" },
  { name: "england-premier-league", url: "https://www.footmercato.net/classement/angleterre/premier-league?partial=1" },
  { name: "coupe-dafrique-des-nations", url: "https://www.footmercato.net/classement/afrique/coupe-dafrique-des-nations?partial=1" },
  { name: "uefa-europa-league", url: "https://www.footmercato.net/classement/europe/uefa-europa-league?partial=1" },
  { name: "france-ligue-2", url: "https://www.footmercato.net/classement/france/ligue-2?partial=1" },
  { name: "italy-serie-a", url: "https://www.footmercato.net/classement/italie/serie-a?partial=1" },
  { name: "germany-bundesliga", url: "https://www.footmercato.net/classement/allemagne/bundesliga?partial=1" },
  { name: "france-national-3", url: "https://www.footmercato.net/classement/france/national-3?partial=1" },
  { name: "saudi-pro-league", url: "https://www.footmercato.net/classement/arabie-saoudite/saudi-pro-league?partial=1" },
  { name: "france-national-2", url: "https://www.footmercato.net/classement/france/national-2?partial=1" },
  { name: "france-national", url: "https://www.footmercato.net/classement/france/national?partial=1" },
  { name: "coupe-du-monde", url: "https://www.footmercato.net/classement/international/coupe-du-monde?partial=1" },
  { name: "portugal-primeira-liga", url: "https://www.footmercato.net/classement/portugal/primeira-liga?partial=1" },
  { name: "england-championship", url: "https://www.footmercato.net/classement/angleterre/league-championship?partial=1" },
  { name: "uefa-europa-conference-league", url: "https://www.footmercato.net/classement/europe/uefa-europa-conference-league?partial=1" },
  { name: "tunisia-ligue-1-pro", url: "https://www.footmercato.net/classement/tunisie/ligue-1-pro?partial=1" },
  { name: "turkey-super-lig", url: "https://www.footmercato.net/classement/turquie/super-lig?partial=1" },
  { name: "coupe-du-monde-feminine", url: "https://www.footmercato.net/classement/international/coupe-du-monde-feminine?partial=1" },
  { name: "euro-feminin", url: "https://www.footmercato.net/classement/europe/euro-feminin?partial=1" },
  { name: "jeux-olympiques", url: "https://www.footmercato.net/classement/international/jeux-olympiques?partial=1" },
  { name: "eliminatoires-cm-europe", url: "https://www.footmercato.net/classement/europe/eliminatoires-cm-europe?partial=1" },
  { name: "coupe-du-monde-des-clubs", url: "https://www.footmercato.net/classement/international/coupe-du-monde-des-clubs?partial=1" },
  { name: "jeux-olympiques-feminins", url: "https://www.footmercato.net/classement/international/jeux-olympiques-feminins?partial=1" },
  { name: "uefa-nations-league", url: "https://www.footmercato.net/classement/europe/uefa-nations-league?partial=1" },
  { name: "euro", url: "https://www.footmercato.net/classement/europe/euro?partial=1" },
  { name: "eliminatoires-euro", url: "https://www.footmercato.net/classement/europe/eliminatoires-euro?partial=1" },
  { name: "coupe-des-confederations", url: "https://www.footmercato.net/classement/international/coupe-des-confederations?partial=1" },
  { name: "uefa-youth-league", url: "https://www.footmercato.net/classement/europe/uefa-youth-league?partial=1" },
  { name: "tournoi-de-france", url: "https://www.footmercato.net/classement/international/tournoi-de-france?partial=1" },
  { name: "copa-america", url: "https://www.footmercato.net/classement/amerique-du-sud/copa-america?partial=1" },
  { name: "euro-u19", url: "https://www.footmercato.net/classement/europe/euro-u19?partial=1" },
  { name: "euro-u21", url: "https://www.footmercato.net/classement/europe/euro-u21?partial=1" },
  { name: "coupe-du-monde-u20", url: "https://www.footmercato.net/classement/international/coupe-du-monde-u-20?partial=1" },
  { name: "coupe-arabe", url: "https://www.footmercato.net/classement/international/coupe-arabe?partial=1" },
  { name: "coupe-dor-concacaf", url: "https://www.footmercato.net/classement/amerique-du-nord/coupe-dor-de-la-concacaf?partial=1" },
  { name: "coupe-feminine-uefa", url: "https://www.footmercato.net/classement/europe/coupe-feminine-uefa?partial=1" },
  { name: "brazil-serie-a", url: "https://www.footmercato.net/classement/bresil/serie-a?partial=1" },
  { name: "argentina-primera-division", url: "https://www.footmercato.net/classement/argentine/primera-division?partial=1" },
  { name: "belgium-division-1a", url: "https://www.footmercato.net/classement/belgique/division-1a?partial=1" }

];

export default LEAGUES;
